### PR TITLE
Final Project

### PR DESCRIPTION
**Pull request by mae6286s**
Merging my final project to your repository.

### CODE REVIEW

**Comment by labarba** [comment]
This is a well-written project, overall. But I did have a hard time ploughing through all the unfamiliar terminology. It seemed at times that you went into some unnecessary detail in the write-up. For example: "a geostationary satellite has no inclination, so it sits at the same node all of the time” Huh? Why do we need to know this? My assessment is that the work would  have benefited from revision and editing (i.e., it reads like a good draft, not a final revision).

“As mentioned above, low earth orbits are determined by an orbital altitude of …” —> I don’t think it _was_ mentioned above.

“we gain the benefit of having stability even with larger step sizes”—> compared to what? (you don’t mention explicit method until the end of the paragraph)

“a time step that large would certainly produce large amounts of error over time” —> in this passage, you’re mixing stability and accuracy

“and the next time step will be given by:” You have some LaTeX there that is not rendered correctly. I think you need a line break before the `\begin{equation}` command.

In your equations, use a backslash with trigonometric functions: `\sin`, `\cos`, etc., so they will be typeset in roman font and distinguishable from variables.
In Eq. (4), one of your denominators with cos(nu) is missing the backslash on `\nu`.

In Eq. (7), compared with Eq. (4), you have switched zeta into k. You do mention this in the passage above, but why not just use k all the time and avoid this?
Under Eq. (7), there is another bit of LaTeX that is not rendered correctly.

"I really wasn't expecting an oscillation in the error curves…” Well, your quantities of interest are periodic, and your error definition is the absolute difference. Is the error proportional to the magnitude of the quantity of interest? What if you were to normalize the error by that magnitude? (a possible problem would arise when the magnitude approaches zero, though).

The section on the System Tool Kit is interesting, but it did not connect with the rest of the project. You gave a nice video of the satellite’s orbit, but is there a way to get the state variables from STK so that you could’ve compared with the results obtained with implicit Runge Kutta? I was left wondering what the point was of this section.

**Typos, grammar, etc.**

… will destroy a satellite, which are typically multi-million dollar investments—> a satellite _is_
factors in it's design —> its
See:
http://www.its-not-its.info

Below is the orbital elements —> Below are
If one were to … they'd see —> agreement: “one” is singular

two body problem —> two-body problem
fourth order accuracy method —> fourth-order accurate method
lets set up —> let’s
occasional —> occasional 
lets get —> let’s
an 313 Euler rotation –> a 313 Euler rotation

we aren't going to anything here —> do anything
lets get into —> let’s
lets plot —> let’s
everything was coded it properly —> delete “it” 
high precision propagators —> high-precision (compound adjective)
tool to use the two-body problem —> on the two-body problem

**Comment by mae6286s** [comment]
Thank you for the feedback, Prof. Barba!

Should I update my project and commit it again?

Thank you,
Stefan

**Comment by labarba** [comment]
Updating the project based on the post-deadline feedback is entirely optional.

**Comment by mae6286s** [comment]
Oh okay, well I'll update it anyway just to make it look better. Thanks!

**Pull request closed without merging**
