### PR TITLE
Completed Final Project

### PR DESCRIPTION
**Pull request by cdigangi8**
Christopher DiGangi

Managing Epidemics with Mathematical Modeling.

### CODE REVIEW

**Comment by cdigangi8** [comment]
I made my final project in the in-class-demo repo that you had us create during one of our classes. For some reason I couldn't get git to transfer the file into the assignment bank repo so I lost the history in this version. I tried following online examples using git mv file dir but I kept getting errors. I decided to just transfer all of the content over to a new notebook.

**Comment by ncclementi** [comment]
Chris, I haven't read it yet, but you should add a licence as we have in at the beginning of our notebooks.

Note: In case anyone is interested in read this notebook, you should download the notebook, otherwise the ipywidgets won't work!

**Comment by cdigangi8** [comment]
Hey, I will certainly add in the license tonight after work! 

Also, I briefly go over how to import ipywidgets using conda, but I noticed my version of conda already had ipywidgets installed.

**Comment by cdigangi8** [comment]
Hey I added the copyright header to the project

**Comment by ncclementi** [comment]
Hey Chris I went through the whole notebook in detail. It's really interesting. I have some comments, if you feel up to fix them, that would be great. 

I've noticed that you explain that the population is fixed in size and other assumptions, that are necessary to understand the eqaution, after you introduce model. In my opinion this assumptions should be before, otherwise it's difficult to understand some points. For example, it took me a while to understand why in the susceptible equation the number of newborns that are not vaccinated contains in its calculation the Average death rate. Thing that is obvious once you know:  the population N is held constant and the birth rate and death rate are equal.

The equation of the solution matrix is missing a u in the left hand side of the equal, but I found out that is a nbviewer problem (in the source code it's present), for some reason it doesn't appear. 

When you change the parameter form the 1st case to the 2nd one, you only change 2 of them, e = .5 ----> e = .1 and gamma = .1 ----> gamma = .5. Then, there is no reason to write all the ones that remain the same again. Or point out which ones are you changing. 

typo:  individuls--------> individuals

**Comment by cdigangi8** [comment]
Hey Naty,

I updated the code with all the changes you pointed out. Do I need to do anything wit the pull request? It looks like it automatically recognizes the new commit so it seems like I don't need to update this one or create a new one?

**Comment by ncclementi** [comment]
Hey Chris, the pull request is updated automatically, so don't worry about that!.

**Comment by labarba** [comment]
This is a nice project, although the numerical problem you chose is quite simple—programming-wise, this work feels rather skimpy (I estimate a half hour of programming effort). It is nice that you introduced `ipywidgets` (but of course this was an idea that I gave you on your pre-project posted on Piazza). Apart from being nice, what do you gain from the widgets, in terms of insight from your model?

Given that this project was numerically unchallenging, I would have expected more discussion of what the model does. Yet, there is only a scant note about the appearance of oscillations with your first chosen set of parameters. Why did you choose these parameters? And what happens in other situations? 

Overall, the treatment of the model is cursory and the programming effort on the low side, which leads me to be underwhelmed, despite the fact that the notebook is nicely put together.

“The most important part of understanding any model is understanding the nomenclature …” —The _most_ important part? well, I think this is an overstatement :-)

“This is a very simplified model because of the complexities of infectious diseases.”  —Yes. And I wish you had elaborated just a bit more here. This sentence really leaves us wondering …

**Typos, grammar, etc.**

the change in Susceptible Indivduals becomes —> Individuals
Now examining the vaccinated individuals —> Now, (comma) … individuals, (comma)
(there are several commas missing elsewhere)

Python should be capitalized: Python not python.

Therfore —> Therefore (after input line `In[23]`)

**Pull request merged**
